TD-4 : Implémentation d'une file dans un tableau dynamique.
PMarcL/IFT2008-Laboratoires-E2017 pull request #4
Opened 2017-05-21 16:05 UTC by errob37

Bonjour Pierre-Marc,

Voici ma proposition d'implémentation d'une file circulaire.

Merci d'avance pour les feedbacks!

2017-05-22 15:15 UTC, PMarcL commented
Cool, je te fais un review. Par contre, je ne le mergerai pas pour l'instant puisqu'on va probablement faire l'exercice dans le prochain lab.

2017-05-22 15:36 UTC, PMarcL requested changes

2017-05-22 15:36 UTC, PMarcL commented on Laboratoire3/FileTableauDynamique/src/File.hpp
> +	__initInstance(p_tailleFile);
On fait rarement ça en c++. Je comprend l'idée de ne pas dupliquer la logique d'initialisation, mais si tu n'utilise pas la liste d'initialisation, le compilateur va insérer du code pour initialiser les attributs de la classe. Donc, ici les attributs sont initialisés deux fois. Ce n'est pas très grave, mais c'est préférable d'utiliser la liste d'initialisation.

2017-05-22 15:36 UTC, PMarcL commented on Laboratoire3/FileTableauDynamique/src/File.h
> +	void __detruire();
Juste un underscore (_) pour les noms des méthodes privées.

2017-05-22 15:36 UTC, PMarcL commented on Laboratoire3/FileTableauDynamique/src/File.h
> +	static const int CARDINALITE_INITIALE = 0; /*!< Cardinalité lors de la création de la file*/
Bonne idée de se mettre des constantes.

2017-05-22 15:36 UTC, PMarcL commented on Laboratoire3/FileTableauDynamique/src/File.hpp
> +	m_queue = (m_queue + 1) % m_tailleMax; // Afin de créer un file circulaire.
FYI, ce pattern est assez connu que tu n'est pas obligé de mettre le commentaire dans un vrai projet. Dans le cadre des labs par contre, c'est bien de le mettre pour que tout le monde comprenne.

2017-05-22 15:36 UTC, PMarcL commented on Laboratoire3/FileTableauDynamique/src/File.hpp
> +
Ici, l'invariant c'est simplement que m_cardinalité > -1, mais ce n'est pas tellement pertinent de le mettre puisque tu n'utilises pas la macro INVARIANTS nul part. Donc, il faudrait enlever le prototype et l'implémentation de cette méthode.

2017-05-22 15:36 UTC, PMarcL commented on Laboratoire3/FileTableauDynamique/src/File.hpp
> +	__initInstance(p_source.m_tailleMax, p_source.m_tete, p_source.m_queue, p_source.m_cardinalite);
Il faudra mettre ça dans la liste d'initialisation du constructeur.

2017-05-22 15:36 UTC, PMarcL commented on Laboratoire3/FileTableauDynamique/src/File.hpp
> +
ligne vide de trop ici

2017-05-22 15:36 UTC, PMarcL commented on Laboratoire3/FileTableauDynamique/src/File.hpp
> +	m_tailleMax = std::min(m_tailleMax * 2, 100);
mmm... Mon guess est que tes constantes static ne sont pas initialisées à l'extérieur de la classe. Il faudrait que tu les initialises dans le haut de ce fichier comme ceci: `template<typename T> const int File<T>::MAX_FILE = 100`. Il y a une autre option avec le mot clé `constexpr` en c++11, mais je ne l'ai jamais utilisé. Si tu es game de faire la recherche et voir comment ça fonctionne, je crois que ça serait une solution plus élégante.

2017-05-22 15:37 UTC, PMarcL commented
Dernier commentaire, il faurait que tu formate tes fichiers en K&R (avec l'accolade à côté des noms de fonctions) pour respecter le standard utilisé dans ce dépôt. Petit détail, mais je préfère être cohérent dans tout le dépôt.

2017-05-22 15:37 UTC, PMarcL commented
Good job btw 🥇

2017-05-23 23:15 UTC, errob37 commented on Laboratoire3/FileTableauDynamique/src/File.hpp
> +	__initInstance(p_tailleFile);
OK.

2017-05-23 23:16 UTC, errob37 commented on Laboratoire3/FileTableauDynamique/src/File.hpp
> +	m_queue = (m_queue + 1) % m_tailleMax; // Afin de créer un file circulaire.
Ok

2017-05-23 23:18 UTC, errob37 commented on Laboratoire3/FileTableauDynamique/src/File.hpp
> +
Done!

2017-05-23 23:30 UTC, errob37 commented on Laboratoire3/FileTableauDynamique/src/File.hpp
> +	__initInstance(p_source.m_tailleMax, p_source.m_tete, p_source.m_queue, p_source.m_cardinalite);
Done!

2017-05-23 23:37 UTC, errob37 commented on Laboratoire3/FileTableauDynamique/src/File.hpp
> +	m_tailleMax = std::min(m_tailleMax * 2, 100);
Le mot clé `constexpr` fonctionne très bien lorsqu'inséré dans une classe. 
La correction de cette revue de code est basé sur ce mot clé.

[Référence constexpr](http://fr.cppreference.com/w/cpp/language/constexpr)

2017-05-23 23:39 UTC, errob37 commented on Laboratoire3/FileTableauDynamique/src/File.hpp
> +
Done!

2017-05-23 23:40 UTC, errob37 commented on Laboratoire3/FileTableauDynamique/src/File.h
> +	void __detruire();
Done!

2022-07-11 18:05 UTC, closed without merging